# CommandReplacer by l1ratch
# Подробнее: https://github.com/l1ratch/CommandReplacer

commands:
  versions:
    aliases: [ ver, vers ]
    text: "&aверсия сервера 1.1.5"
    command:
      - "say Hello!"
      - "time set day"
  plugin:
    aliases: [ pl ]
    text: "&cПлагинов нет"
    command:
      - "plugin list"
  players:
    aliases: [ who, online ]
    text: "&eСейчас онлайн: %online_players%"
    command:
      - "list"
  time:
    aliases: [ currenttime, now ]
    command:
      - "time query daytime"